$(document).ready(function(){
$('#preloader').fadeOut('slow');
const reports=[
['Sales','sales_summary','Sales Summary','mdi-chart-bar'],['Sales','sales_detailed','Sales Detailed','mdi-file-document'],['Sales','customer_wise_sales','Customer-wise Sales','mdi-account-cash'],['Sales','product_wise_sales','Product-wise Sales','mdi-package-variant'],['Sales','sales_due','Sales Due','mdi-calendar-alert'],['Sales','customer_payment','Customer Payment','mdi-cash-plus'],
['Purchase','purchase_summary','Purchase Summary','mdi-chart-bar'],['Purchase','purchase_detailed','Purchase Detailed','mdi-file-document'],['Purchase','supplier_wise_purchase','Supplier-wise Purchase','mdi-truck'],['Purchase','product_wise_purchase','Product-wise Purchase','mdi-package-down'],['Purchase','purchase_due','Purchase Due','mdi-calendar-alert'],['Purchase','supplier_payment','Supplier Payment','mdi-cash-minus'],
['Expense','expense_summary','Expense Summary','mdi-chart-pie'],['Expense','expense_detailed','Expense Detailed','mdi-receipt'],['Expense','payment_mode_expense','Payment Mode-wise Expense','mdi-bank'],
['Outstanding','customer_outstanding','Customer Outstanding','mdi-account-alert'],['Outstanding','supplier_outstanding','Supplier Outstanding','mdi-truck-alert'],['Outstanding','customer_ageing','Customer Ageing','mdi-timer-sand'],['Outstanding','supplier_ageing','Supplier Ageing','mdi-timer-sand'],
['Stock','current_stock','Current Stock','mdi-warehouse'],['Stock','low_stock','Low Stock','mdi-alert-box'],['Stock','batch_stock','Batch-wise Stock','mdi-barcode'],['Stock','stock_movement','Stock Movement','mdi-swap-horizontal'],['Stock','stock_valuation','Stock Valuation','mdi-currency-inr'],
['Profit','gross_profit','Gross Profit','mdi-trending-up'],['Profit','net_profit','Net Profit','mdi-finance'],['Profit','product_profit','Product Profit','mdi-package-variant-closed'],
['GST','sales_gst','Sales GST','mdi-percent'],['GST','purchase_gst','Purchase GST','mdi-percent'],['GST','gst_summary','GST Summary','mdi-calculator'],
['Master','customer_master','Customer Master','mdi-account-group'],['Master','supplier_master','Supplier Master','mdi-truck'],['Master','product_master','Product Master','mdi-package'],
['Admin','user_wise_sales','User-wise Sales','mdi-account-star'],['Admin','cancelled_deleted','Cancelled / Deleted','mdi-delete-alert']
];
let selected='sales_summary',timer=null; renderCards(); loadReport();
$('#loadReportBtn,#fromDate,#toDate').on('click change',loadReport); $('#reportSearch').on('keyup',function(){clearTimeout(timer);timer=setTimeout(loadReport,400)});
$(document).on('click','.report-card',function(){selected=$(this).data('key');$('.report-card').removeClass('active');$(this).addClass('active');loadReport()});
function renderCards(){let h='',g='';$.each(reports,function(_,r){if(g!==r[0]){g=r[0];h+=`<div class="col-12"><h5 class="mt-3 mb-2">${e(g)} Reports</h5></div>`}h+=`<div class="col-md-4 col-xl-3"><div class="card report-card ${r[1]===selected?'active':''}" data-key="${r[1]}"><div class="card-body py-3"><div class="d-flex align-items-center"><span class="avatar-title bg-primary-subtle text-primary rounded-circle me-3"><i class="mdi ${r[3]} font-size-20"></i></span><div><h6 class="mb-0">${e(r[2])}</h6><small class="text-muted">${e(r[0])}</small></div></div></div></div></div>`});$('#reportCards').html(h)}
function loadReport(){$('#reportHead').html('<tr><th>Loading...</th></tr>');$('#reportBody').html('<tr><td class="text-center text-muted">Loading...</td></tr>');$('#reportFoot,#summaryBox').html('');$.ajax({url:window.BASE_URL+'api/all-reports.php',type:'GET',dataType:'json',data:{action:'list',report_key:selected,from_date:$('#fromDate').val(),to_date:$('#toDate').val(),search:$('#reportSearch').val()},success:function(r){if(r.status===true)renderReport(r.data||{});else{$('#reportHead').html('<tr><th>Error</th></tr>');$('#reportBody').html(`<tr><td class="text-center text-danger">${e(r.message||'Error')}</td></tr>`);toast('error',r.message||'Error')}},error:function(x){console.log(x.responseText);$('#reportHead').html('<tr><th>Error</th></tr>');$('#reportBody').html('<tr><td class="text-center text-danger">Server error.</td></tr>')}})}
function renderReport(d){let rows=d.rows||[],cols=d.columns||[],filters=d.filters||{};$('#reportTitle').text(d.title||'Report');$('#recordCount').text((d.count||rows.length||0)+' Records');$('#reportPeriod').text((filters.from_date===filters.to_date?'Date: '+filters.from_date:'Date: '+filters.from_date+' to '+filters.to_date)+(filters.search?' | Search: '+filters.search:''));renderSummary(d.totals||{});renderTable(cols,rows,d.totals||{}) }
function renderSummary(t){let keys=Object.keys(t||{}),h='';$.each(keys,function(_,k){h+=`<div class="col-md-3 col-xl-2"><div class="border rounded p-2 mb-2"><small class="text-muted">${label(k)}</small><h6 class="mb-0">${money(k)?'₹':''}${nf(t[k])}</h6></div></div>`});$('#summaryBox').html(h)}
function renderTable(cols,rows,totals){let head='<tr><th>#</th>';$.each(cols,function(_,c){head+=`<th>${e(c)}</th>`});head+='</tr>';$('#reportHead').html(head);if(!rows.length){$('#reportBody').html(`<tr><td colspan="${cols.length+1}" class="text-center text-muted">No records found.</td></tr>`);return}let keys=Object.keys(rows[0]),h='';$.each(rows,function(i,row){h+=`<tr><td>${i+1}</td>`;$.each(keys,function(_,k){let v=row[k];h+=($.isNumeric(v)&&k!=='id'?`<td class="text-end">${money(k)?'₹':''}${nf(v)}</td>`:`<td>${e(v)}</td>`)});h+='</tr>'});$('#reportBody').html(h);let f='<tr><th>Total</th>';$.each(keys,function(_,k){f+=totals.hasOwnProperty(k)?`<th class="text-end">₹${nf(totals[k])}</th>`:'<th></th>'});f+='</tr>';$('#reportFoot').html(Object.keys(totals).length?f:'')}
function money(k){return /(amount|total|tax|gst|value|paid|due|rate|cost|profit|outstanding|opening|current|sales|purchase|expense|stock|price|retail|wholesale)/i.test(k)}
function label(k){return String(k).replace(/_/g,' ').replace(/\b\w/g,l=>l.toUpperCase())} function nf(v){return parseFloat(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})} function e(v){return $('<div>').text(v===null||v===undefined?'':v).html()} function toast(t,m){if(typeof showToast==='function')showToast(t,m,5000);else console.log(t+': '+m)}
});
